name: Continuous Integration - Documentation

on: [push, pull_request]

jobs:
  continuous-integration-documentation:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.13]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Environment Variables
        run: |
          echo "CI_PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV
          echo "CI_PACKAGE=colour_demosaicing" >> $GITHUB_ENV
          echo "CI_SHA=${{ github.sha }}" >> $GITHUB_ENV
          echo "MPLBACKEND=AGG" >> $GITHUB_ENV
          echo "COLOUR_SCIENCE__DOCUMENTATION_BUILD=True" >> $GITHUB_ENV
        shell: bash
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get --yes install latexmk texlive-full
      - name: Install uv
        run: |
          pip install uv
        shell: bash
      - name: Install Package Dependencies
        run: |
          uv sync --all-extras --no-dev
          uv run python -c "import imageio;imageio.plugins.freeimage.download()"
        shell: bash
      - name: Build Documentation
        run: |
          uv run invoke docs
        shell: bash
