name: Continuous Integration - Static Type Checking

on: [push, pull_request]

jobs:
  continuous-integration-static-type-checking:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [macOS-latest]
        python-version: [3.13]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Environment Variables
        run: |
          echo "CI_PACKAGE=colour_demosaicing" >> $GITHUB_ENV
        shell: bash
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Package Dependencies
        run: |
          cat requirements.txt | grep -Eo '(^[^#]+)' | xargs -n 1 pip install || true
      - name: Static Type Checking
        run: |
          pyright --threads --skipunannotated
